[env]
EMAILJS_SERVICE_ID = "service_n9a3k6e"
EMAILJS_TEMPLATE_ID = "template_5vr8za6"
EMAILJS_PUBLIC_KEY = "AHvm1NQh5ANq_mT4D"
EMAILJS_USER_ID = "saffronemporial@gmail.com"
EMAILJS_PRIVATE_KEY= qEX03hF6lAhPLnUrUke5Y
